#!/usr/bin/env python

import sys
import json
import subprocess


def get_locks():
    locks = subprocess.check_output(
            ["git", "lfs", "locks", "--json"],
            stderr=sys.stderr,
            stdin=sys.stdin
            )
    locks = locks.decode()
    return [lock["path"] for lock in json.loads(locks)]


def get_staged_files():
    lines = subprocess.check_output(
            ["git", "status", "--porcelain"],
            stderr=sys.stderr,
            stdin=sys.stdin
            )
    lines = lines.decode().split("\n")
    return [l[3:].strip() for l in lines if (l and l[0] not in (" ", "?"))]


staged = get_staged_files()
locks = get_locks()

staged_locked_files = []

for path in staged:
    if path in locks:
        staged_locked_files.append(path)

if staged_locked_files:
    print("\x1B[1;37;41m Commit rejected, you staged locked file(s): \x1B[0m")
    print("\n".join(["  * %s" % path for path in staged_locked_files]))
    sys.exit(1)


# vim:ft=python
